version: "3.8"
services:
  anythink-backend-node:
    build: ./backend
    container_name: anythink-backend-node
    command: sh -c "cd backend && yarn install && /wait-for-it.sh mongodb-node:27017 -q -t 60 && yarn dev"

    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb-node:27017/anythink-market
      - GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN=${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}
    working_dir: /usr/src
    volumes:
      - ./:/usr/src/
      - /usr/src/backend/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - "mongodb-node"

  anythink-frontend-react:
    build: ./frontend
    container_name: anythink-frontend-react
    command: sh -c "cd frontend && yarn install && /wait-for-it.sh anythink-backend-node:3000 -t 120 --strict -- curl --head -X GET --retry 30 --retry-connrefused --retry-delay 1 anythink-backend-node:3000/api/ping && yarn start"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - REACT_APP_BACKEND_URL=${CODESPACE_BACKEND_URL:-http://localhost:3000}
      - WDS_SOCKET_PORT=${CODESPACE_WDS_SOCKET_PORT:-3001}
    working_dir: /usr/src
    volumes:
      - ./:/usr/src/
      - /usr/src/frontend/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - "anythink-backend-node"

  mongodb-node:
    container_name: mongodb-node
    restart: always
    image: mongo
    logging:
      driver: none
    volumes:
      - ~/mongo/data:/data/db
    ports:
      - '27017:27017'

  anythink-ack:
    build: ./frontend
    container_name: anythink-ack
    command: sh -c "/wait-for-it.sh anythink-frontend-react:3001 -q -t 1000 && ./anythink_ack.sh"
    working_dir: /usr/src
    volumes:
      - ./:/usr/src/
    depends_on:
      - "anythink-frontend-react" 
