apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.backend.serviceName }}
  name: {{ .Values.backend.serviceName }}
spec:
  ports:
    - name: "{{ .Values.backend.containerPort }}"
      port: {{ .Values.backend.containerPort }}
      targetPort: {{ .Values.backend.containerPort }}
  selector:
    app: {{ .Values.backend.serviceName }}
